server:
  port: 8080
spring:
  datasource:
    # sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/jixian.db


mybatis-flex:
  # mapper xml的位置
  mapper-locations: classpath:mappers/*Mapper.xml
  # 扫描实体类自动设置别名
  type-aliases-package: com.rj.backendjixian.entity
  configuration:
    map-underscore-to-camel-case: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  # 文档地址
  swagger-ui:
    path: /docs
  # 是否启用接口文档
  api-docs:
    enabled: true
files:
  upload:
    fileUploadPath: upload
    permittedFileType: jpg,jpeg,ico,tiff,gif,svg,webp,png,bmp