server:
  port: 8080
spring:
  datasource:
    # sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/jixian.db


mybatis-flex:
  # mapper xml的位置
  mapper-locations: classpath:mappers/*Mapper.xml
  # 扫描实体类自动设置别名
  type-aliases-package: com.rj.backendjixian.entity
  configuration:
    map-underscore-to-camel-case: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  # 文档地址
  swagger-ui:
    path: /docs
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true
  # 是否启用接口文档
  api-docs:
    enabled: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#jwt:
#  key: tCo2ZgpY9JdzSVbuJ25f1r77NXJXti7g #密钥
#  Token_EXP: "#{1000 * 60 * 60 * 24}" #过期时间 1天